In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
print("Slicing", arr[2:5])
print("Slicing with step", arr[1:7:2])

Slicing [2 3 4]
Slicing with step [1 3 5]


In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("An element: ", arr_2d[1, 2])
print("A row: ", arr_2d[0])
print("A column: ", arr_2d[:, 1])


An element:  6
A row:  [1 2 3]
A column:  [2 5 8]


In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1, 4], 
                            [1, 5, 9], 
                            [2, 6, 5]])
print("Sorted along axis 0:\n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted along axis 1:\n", np.sort(arr_2d_unsorted, axis=1))

Sorted [1 1 2 3 4 5 6 9]
Sorted along axis 0:
 [[1 1 4]
 [2 5 5]
 [3 6 9]]
Sorted along axis 1:
 [[1 3 4]
 [1 5 9]
 [2 5 6]]


In [8]:
numbers = np.arange(99)
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [9]:
mask = (numbers > 50) & (numbers < 60)
filtered_numbers = numbers[mask]
print("Numbers between 50 and 60:", filtered_numbers)

Numbers between 50 and 60: [51 52 53 54 55 56 57 58 59]


In [10]:
indices = [22, 34, 56]
print("Elements at indices 22, 34, and 56:", numbers[indices])

Elements at indices 22, 34, and 56: [22 34 56]


In [12]:
where_result = np.where(numbers % 2 == 0)
print("Even numbers:", numbers[where_result])

Even numbers: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [13]:
condition_array = np.where(numbers > 50, numbers*2, numbers)
print("Conditionally modified array:", condition_array)

Conditionally modified array: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196]


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Concatenated array:", np.concatenate((arr1, arr2)))

Concatenated array: [1 2 3 4 5 6]


In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
print(a.shape == b.shape)

True


In [17]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
result = np.vstack((original, new_row))
print("Stacked array:\n", result)
new_col = np.array([[7], [8], [9]])
result_col = np.hstack((result, new_col))
print("Horizontally stacked array:\n", result_col)

Stacked array:
 [[1 2]
 [3 4]
 [5 6]]
Horizontally stacked array:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
arr = np.arange(10)
modified_arr = np.delete(arr, [2, 5])
print("Modified array after deletion:", modified_arr)