In [2]:
import numpy as np

In [3]:
arr_1d =  np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [4]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
full = np.full((2, 3), 7)
print(full)

[[7 7 7]
 [7 7 7]]


In [7]:
random = np.random.random((2, 3))
print(random)

[[0.5392652  0.24442561 0.68004612]
 [0.53698624 0.1636072  0.75071653]]


In [8]:
sequence = np.arange(0, 10, 3)
print(sequence)

[0 3 6 9]


In [9]:
vector = np.array([1, 2, 3])
print(vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Dinmension: ", arr.ndim)
print("Data type: ", arr.dtype)

Shape:  (2, 3)
Size:  6
Dinmension:  2
Data type:  int64


In [ ]:
arr = np.arange(16)
print("Original array: ", arr)
reshaped_arr = arr.reshape(4, 4)
print("Reshaped array: ", reshaped_arr)
flattened_arr = reshaped_arr.flatten()
print("Flattened array: ", flattened_arr)
raveled_arr = reshaped_arr.ravel()
print("Raveled array: ", raveled_arr)

transposed_arr = reshaped_arr.T
print("Transposed array: ", transposed_arr)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
